"""Add teacher relationship to sections

Revision ID: 98b49eebb059
Revises: cbf10ca1cf1b
Create Date: 2026-02-25 04:32:02.188671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b49eebb059'
down_revision: Union[str, Sequence[str], None] = 'cbf10ca1cf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('class_teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sections', 'teacher_profiles', ['class_teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'class_teacher_id')
    # ### end Alembic commands ###
